config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'records/my_index' => 'records#my_index'
  get 'records/report' => 'records#report'
  resources :records

  root 'records#new'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user

  validates :user_id, :contact_type, :patron, :time_spent, :question, presence: true
  validates :satisfaction, :inclusion => {:in => [true, false], :message=>"cannot be blank."}

  def self.created_within(start_date, end_date)
    where("created_at BETWEEN ? AND ?", start_date, end_date)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  crop_attached_file :avatar
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  



  protected

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    new_record_path
  end

  def after_sign_up_path_for(resource)
    new_record_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :avatar, :avatar_original_w, :avatar_original_h, :avatar_box_w, :avatar_crop_x, :avatar_crop_y, :avatar_crop_w, :avatar_crop_h, :avatar_aspect) }
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!

  
  def index
    if params[:start] && params[:end]
      @records = Record.created_within(params[:start], params[:end])
      # respond_to do |format|
      #   format.json {render :json => @result}
      # end
    else
      @records = Record.all
      # respond_to :html
    end
  end

  def my_index
    @records = current_user.records.all

  end

  def report

    
  end

  def new
    @record = Record.new
  end

  def create
    @record = current_user.records.build(record_params)
    if @record.save
      redirect_to new_record_path, notice: 'Record created successfully'
    else
      render 'records/new'
    end

  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])

    if @record.update_attributes(record_params)
      redirect_to records_path
    else
      render :edit
    end
  end

  def destroy
    @record = Record.find(params[:id])
    @record.destroy
    redirect_to records_url
  end
end

private
def record_params
  params.require(:record).permit(:user_id, :contact_type, :patron, :question, :time_spent, :satisfaction, :bloomberg, :capital_iq, :factset, :thomsonone, :other_inquiry_details, :course_code, :other_res, :other_res_details)
end

    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LabStatApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'app_nav_bar' %>
	<% if flash[:notice] %>
		<p class="alert alert-success">
			<%= notice %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
		</p>
	<% end %>	
	<% if flash[:alert] %>
		<p class="alert alert-danger">
			<%= alert %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		  	<span aria-hidden="true">&times;</span>
			</button>
		</p>
	<% end %>	

	<%= yield %>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UTSC Finance Lab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="devise-form container-fluid">
	<% if flash[:notice] %>
		<p class="alert alert-success">
			<%= notice %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>
		</p>
	<% end %>	
	<% if flash[:alert] %>
		<p class="alert alert-danger">
			<%= alert %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		  	<span aria-hidden="true">&times;</span>
			</button>
		</p>
	<% end %>	
	<div class='row col-md-offset-3'>
		<%= link_to image_tag("utsc_brand.png", :id=>"brand"), "http://www.utsc.utoronto.ca/home/" %>
		<h1 id="finlab-title">Finance Lab Statistics</h1>
	</div>
	<!-- <p>Life it is not just a series of calculations and a sum total of statistics, it's about experience, it's about participation, it is something more complex and more interesting than what is obvious.</p> -->
	<br>
	<div class="devise-box col-sm-6 col-sm-offset-3">
	<%= yield %>
</div>
</body>
</html>

app/views/records/_app_nav_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
<!--       <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <!-- <a class="navbar-brand" href="http://www.utsc.utoronto.ca/home/"> -->
        <%= link_to image_tag('utsc_brand_square.png', :height=>"25px"), "http://www.utsc.utoronto.ca/home/", :target => "_blank", :class=>'navbar-brand' %>
      <!-- </a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/records/new">New Form<span class="sr-only">(current)</span></a></li>
      </ul>

      <p class="nav navbar-text" id="timeNow"></p>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Records <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "By me", records_my_index_path %></li>
            <li><%= link_to "By all users", records_path %></li>
   <!--          <li><a href="#">Something else here</a></li> -->
            <li class="divider"></li>
            <li><%= link_to "Report", records_report_path %></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <% if user_signed_in? %>
          <li>
            <%= link_to 'Edit profile', edit_user_registration_path %>
          </li>
          <li>    
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
        <% else %>
            <li>
              <%= link_to('Login', new_user_session_path) %>  
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/records/_form.html.erb
<%= form_for @record do |f| %>

	<% if @record.errors.any? %>
		<div class="alert alert-danger" role="alert" id="error_explanation">
  		<h2><%= pluralize(@record.errors.count, "error") %> prohibited this form from being saved:</h2>
		  <ul>
		  		<% @record.errors.full_messages.each do |msg| %>
		    		<li><%= msg %></li>
		  		<% end %>
		  </ul>
		</div>
	<% end %>
	
	<!-- First Panel -->
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Inquiry format</h3>
		</div>
		<div class="panel-body">
			<!-- Question 1 -->
			<%= f.label :contact_type, "How is the inquiry recieved?" %> <br>
			<div class="radio-inline">
				<%= f.radio_button :contact_type, "phone" %>
				<%= f.label :contact_type, "By phone", :value=>"phone"%>
			</div>
			<div class="radio-inline">
				<%= f.radio_button :contact_type, "email" %>
				<%= f.label :contact_type, "By e-mail", :value=>"email" %>
			</div>
			<div class="radio-inline">
				<%= f.radio_button :contact_type, "person" %>
				<%= f.label :contact_type, "In person", :value=>"person" %>
			</div>
			<br>
			<br>
			
			<!-- Question 2 -->
			<%= f.label :patron, "Tell us about the patron." %> <br>
			<div class="radio-inline">
				<%= f.radio_button :patron, "student", :checked => true %>
				<%= f.label :patron, "Student", :value=>"student" %>
			</div>
			<div class="radio-inline">
				<%= f.radio_button :patron, "faculty" %>
				<%= f.label :patron, "Faculty member", :value=>"faculty" %>
			</div>
			<div class="radio-inline">
				<%= f.radio_button :patron, "other" %>
				<%= f.label :patron, "Other", :value=>"other" %>
			</div>

		</div>
	</div>
	
	<!-- Second panel -->
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Inquiry detail</h3>
		</div>
		<div class="panel-body">
			<!-- Question 3 -->
			<%= f.label :question, "What is the Inquiry about?" %> <br>
			<%= f.select :question, options_for_select([['General Inquiries','general'],['Technical Issues','techincal'],['Career Advice','career'],['Academic & Researches','research'],['Other','other', :id=>'other-inquiry-option']], :selected => f.object.question), {:prompt=>"Please choice one of the following..."}, :class=>'form-control' %>
			<br>
			<% if @record.other_inquiry_details.blank? %>
				<%= f.text_area :other_inquiry_details, :placeholder=>"Please fill in the details.", :hidden=>true, :class=>"form-control" %> 
			<% else %>
				<%= f.text_area :other_inquiry_details, :placeholder=>"Please fill in the details.",  :class=>"form-control" %> <br>
			<% end %>

			<div class="form-inline">
				<%= f.label :course_code %>
				<%= f.text_field :course_code, :placeholder=>'*optional', :class=>"form-control" %>
			</div>
			<br>
			<!-- Question 4 -->
			<%= f.label :time_spent, "How long did it take you to resolve patron's question?" %> <br>
			<div class="radio-inline">
				<%= f.radio_button :time_spent, 3, :checked=>true %>
				<%= f.label :time_spent, "3 mins or less", :value=>3 %>
			</div>
			<div class="radio-inline">
				<%= f.radio_button :time_spent, 20 %>
				<%= f.label :time_spent, "Bewteen 3 to 20 mins", :value=>20 %>
			</div>	
			<div class="radio-inline">
				<%= f.radio_button :time_spent, 30 %>
				<%= f.label :time_spent, "More than 30 mins", :value=>30 %>
			</div>
		</div>
	</div>

	<!-- Third panel -->
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Lab resources</h3>
		</div>
		<div class="panel-body">
			<!-- Quesiton 5 -->
			<div class="checkbox-inline">
				<%= f.check_box :bloomberg %>
				<%= f.label :bloomberg, image_tag('Bloomberg.png', :height=>'50px') %>
			</div>
			<div class="checkbox-inline">
				<%= f.check_box :capital_iq %>
				<%= f.label :capital_iq, image_tag('capIQ.png', :height=>'50px') %>
			</div>
			<div class="checkbox-inline">
				<%= f.check_box :factset %>
				<%= f.label :factset, image_tag('factsetlogo.png', :height=>'50px') %>
			</div>
			<div class="checkbox-inline">
				<%= f.check_box :thomsonone %>
				<%= f.label :thomsonone, image_tag('thomson.jpeg', :height=>'50px') %>
			</div>
			<div class="checkbox-inline">
				<%= f.check_box :other_res %>
				<%= f.text_area :other_res_details, :placeholder=>"Other...", :class=>"form-control" %>
			</div>
		</div>
	</div>

	<!-- Question 6 -->
	<%= f.label :satisfaction, "Was the patron satisfied?" %> <br>
	<div class="radio-inline">
		<%= f.radio_button :satisfaction, true %>
		<%= f.label :satisfaction, "Yes", :value=>true %>
	</div>
	<div class="radio-inline">
		<%= f.radio_button :satisfaction, false %>
		<%= f.label :satisfaction, "No", :value=>false %>
	</div>	
	<br>
	<br>

	<%= f.submit "Save", :class=>"btn btn-primary btn-lg" %> 

	<% end %> <br>

app/views/records/create.html.erb
<h1>Records#create</h1>
<p>Find me in app/views/records/create.html.erb</p>

app/views/records/destroy.html.erb
<h1>Records#destroy</h1>
<p>Find me in app/views/records/destroy.html.erb</p>

app/views/records/edit.html.erb
<div class="container">
	<div class="page-header">
		<h1>Edit exising record <small>Please answer all quesitons</small></h1>
	</div>
	<div class="row alert alert-warning">
		<!-- <div class="panel-body"> -->
			<!-- <div class="col-md-10">		 -->
				<p class="col-md-10">Record #<%= @record.id %> was initially created at <%= @record.created_at.strftime("%e %b %Y %H:%M:%S%p") %> by <%= @record.user.first_name %> <%= @record.user.last_name %><br>Last updated at: <%= @record.updated_at.strftime("%e %b %Y %H:%M:%S%p") %></p>
			<!-- </div> -->
			<!-- <div class="col-md-2"> -->
				<%= button_to "Delete record", @record, method: :delete, data: {confirm: "Are you sure you want to delete this record?"}, :class=>"btn btn-danger col-md-2" %>
			<!-- </div> -->
		<!-- </div> -->
	</div>


<%= render 'form' %>
<%= link_to "Back", :back %>


</div> <!-- container -->

app/views/records/index.html.erb
<div class="container">
	<div class="page-header">
		<h1>All records <small>entered by all FLAs</small></h1>
	</div>
	<table class="table table-condensed table-hover record_index">
		<thead>
			<td>Record #</td>
			<td>Person in Charge</td>
			<td>Recorded at</td>
			<td>Contact type</td>
			<td>Patron</td>
			<td>Question</td>
			<td>Time spent</td>
			<td>Satisfied?</td>
			<!-- <td></td> -->
		</thead>
		<tbody>
			<% @records.each do |record| %>
				<tr>
					<td><%= record.id %></td>
					<td><%= record.user.first_name %> <%=record.user.last_name %></td>
					<td><%= record.created_at.strftime("%e %b %Y %H:%M:%S%p") %></td>
					<td><%= record.contact_type %></td>
					<td><%= record.patron %></td>
					<td><%= record.question %></td>
					<td><%= record.time_spent %></td>
					<td><%= record.satisfaction %></td>
					<td><%#= link_to "Edit", edit_record_path(record) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>


</div>

app/views/records/my_index.html.erb
<div class="container">
	<div class="page-header">
		<h1>My records <small>owned by <%= current_user.first_name %> <%= current_user.last_name %></small></h1>
	</div>
	<table class="table table-condensed table-hover record_index">
		<thead>
			<td>Record #</td>
			<td>Recorded at</td>
			<td>Contact type</td>
			<td>Patron</td>
			<td>Question</td>
			<td>Time spent</td>
			<td>Satisfied?</td>
			<td></td>
		</thead>
		<tbody>
			<% @records.each do |record| %>
				<tr>
					<td><%= record.id %></td>
					<td><%= record.created_at.strftime("%e %b %Y %H:%M:%S%p") %></td>
					<td><%= record.contact_type %></td>
					<td><%= record.patron %></td>
					<td><%= record.question %></td>
					<td><%= record.time_spent %></td>
					<td><%= record.satisfaction %></td>
					<td><%= link_to "Edit", edit_record_path(record) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>


</div>

app/views/records/new.html.erb
<div class="jumbotron">
	<%= image_tag current_user.avatar.url(:thumb) %>
	<h1>Hello, I am <%= current_user.first_name %>!</h1>
	<h2>It's <span id="hourNow"></span>, need help on <em id="typingEffect"></em></h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis libero magni veniam, totam architecto distinctio assumenda aliquid eveniet accusantium amet rerum fugiat. Sint libero odio sed enim facilis unde possimus.</p>
	<p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

<div class="container">
	<div class="page-header">
		<h1>Data Collection Form <small>Please answer all quesitons</small></h1>
	</div>

<%= render 'form' %>


</div> <!-- container -->

app/views/records/report.html.erb
<div class="container">
	<div class="page-header">
		<h1>User statistics <small id="dateRangeDisplay">all time</small></h1>
	</div>
		<div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
		    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
		    <span></span> <b class="caret"></b>
		</div>

app/views/records/update.html.erb
<h1>Records#update</h1>
<p>Find me in app/views/records/update.html.erb</p>